image: fedora:24

services:
  - redis:latest

before_script:
   - echo 'deltarpm=0' >> /etc/dnf/dnf.conf
   - dnf -y update
   - dnf -y install git gzip java-1.8.0-openjdk nodejs redis tar wget which procps-ng curl
   - bin/bootstrap
   - bin/datastore start
   - npm install

all_tests:
  script:
   - bin/test redis://redis
